server:
  port: 9000

spring:
  application:
    name: auth-server

  security:
    oauth2:
      authorizationserver:
        client:
          api-service-client:
            registration:
              client-id: api-service
              client-secret: "{noop}secret123"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - apis:read

jwt:
  issuer-uri: http://localhost:9000

logging:
  level:
    org.springframework.security: DEBUG